-- Migration 014: Add all remaining achievement tracking columns

-- user_stats
ALTER TABLE user_stats
    ADD COLUMN IF NOT EXISTS pp_check_ones              INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS ip_check_ones              INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS sp_check_ones              INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS pp_check_maxes             INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS ip_check_maxes             INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS sp_check_maxes             INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS checks_while_debuffed_won  INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS checks_total_zero_or_below INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS stat_one_check_maxes       INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS last_pp_check_won          BOOLEAN,
    ADD COLUMN IF NOT EXISTS last_ip_check_won          BOOLEAN,
    ADD COLUMN IF NOT EXISTS last_sp_check_won          BOOLEAN,
    ADD COLUMN IF NOT EXISTS miss_count                 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS bap_miss_count             INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS whispers_sent              INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS whispers_received          INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS mentions_received          INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS summons_fired              INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS campaigns_created          INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS lore_entries_created       INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS images_shared              INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS scene_updates              INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS items_gifted               INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS npcs_created               INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS battles_initiated          INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS npc_damage_dealt           INTEGER NOT NULL DEFAULT 0;

-- character_stats
ALTER TABLE character_stats
    ADD COLUMN IF NOT EXISTS pp_check_ones              INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS ip_check_ones              INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS sp_check_ones              INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS pp_check_maxes             INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS ip_check_maxes             INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS sp_check_maxes             INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS checks_while_debuffed_won  INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS checks_total_zero_or_below INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS stat_one_check_maxes       INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS last_pp_check_won          BOOLEAN,
    ADD COLUMN IF NOT EXISTS last_ip_check_won          BOOLEAN,
    ADD COLUMN IF NOT EXISTS last_sp_check_won          BOOLEAN,
    ADD COLUMN IF NOT EXISTS miss_count                 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS bap_miss_count             INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS whispers_sent              INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS mentions_received          INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS summons_fired              INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS npc_damage_dealt           INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS lore_entries_created       INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS images_shared              INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS scene_updates              INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS items_gifted               INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS npcs_created               INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS battles_initiated          INTEGER NOT NULL DEFAULT 0;
